resolver: lts-3.7
packages:
- 'verdict'
- 'verdict-json'
- 'verdict-quickcheck'
- 'verdict-db'
extra-deps:
- attoparsec-0.13.0.1
- aeson-0.10.0.0
- markdown-unlit-0.2.0.1
- generics-sop-0.2.0.0
flags: {}
extra-package-dbs: []
